version: "3.8"

services:
  db:
    image: postgres:15.7
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: links
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./config.yaml:/config.yaml
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "/usr/local/bin/link-shortener-svc migrate up && /usr/local/bin/link-shortener-svc run service",
      ]

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/www/html:/usr/share/nginx/html
    depends_on:
      - api

volumes:
  pgdata:
